# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('score_document', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Document to store information related to scoring')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.Keywords')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('score_document', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Document to store information related to scoring')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.Keywords')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
