# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_auto_20170825_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityscore',
            name='score_document',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Document to store information related to scoring'),
        ),
    ]
