# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_auto_20170825_1526'),
        ('search_engine', '0004_auto_20170825_1513'),
    ]

    operations = [
    ]
