# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0002_auto_20170825_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryKeywordStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('score_doc', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.Keywords')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='querykeywordstore',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_parser.QueryStore'),
        ),
    ]
