# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querykeywordstore',
            name='score_doc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
