# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_parser', '0002_auto_20170825_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='querykeywordstore',
            options={'verbose_name': 'Query Keyword Score', 'verbose_name_plural': 'Query Keyword Scores'},
        ),
        migrations.AlterModelOptions(
            name='querystore',
            options={'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
    ]
